require("basic")
require("keymap")
require("neovide")
require("plugin")

require("plugins.theme")
require("plugins.lsp")
require("plugins.mini")
require("plugins.treesitter")
require("plugins.markdown")
require("plugins.terminal")
require("plugins.myfun")
