vim.o.autochdir = true						-- 启用自动切换目录
vim.o.bufhidden = "hide"					-- 打开其他 buffer 时隐藏
vim.o.clipboard = "unnamedplus"					-- 开启系统剪贴板
vim.o.complete = ".,w,b,u,t,i,kspell"				-- 设置补全源
vim.o.completeopt = "menuone,preview,popup,preinsert"		-- 设置补全样式
vim.o.cursorline = true						-- 高亮当前行
vim.o.expandtab = true						-- 启用制表符转空格
vim.o.fileignorecase = true					-- 启用文件名忽略大小写
vim.o.icon = true						-- 启用终端图标设置
vim.o.infercase = true                                          -- 启用大小写推断
vim.o.nrformats = "bin,hex,alpha,octal"                         -- 启用所有数字格式
vim.o.number = true                                             -- 启用行号
vim.o.wrap = false                                              -- 代码过长时自动续行
vim.o.pumheight = 10                                            -- 补全菜单的高度
vim.o.shell = "cmd"                                             -- 默认终端
vim.o.shiftround = true                                         -- 启用缩进对齐
vim.o.shiftwidth = 4                                            -- 设置缩进 4 空格
vim.o.showtabline = 0                                           -- 顶部不显示标签页
vim.o.signcolumn = "number"                                     -- 附加信息与行号合并
vim.o.smartcase = true                                          -- 启用智能大小写搜索
vim.o.splitright = true                                         -- 新窗口出现在右侧
vim.o.softtabstop=4                                             -- 按一次 Tab 键插入 4 个空格
vim.o.syntax = "enable"                                         -- 启用语法高亮
vim.o.timeoutlen = 500                                          -- 设置映射超时
vim.o.undofile = true                                           -- 启用持久化撤销
vim.o.updatetime = 500                                          -- 设置更新时间
vim.o.wildignorecase = true                                     -- 启用命令行补全忽略大小写
-- vim.o.winborder = "rounded"                                  -- 设置悬浮窗边框
vim.o.mousemoveevent = true                                     -- 启用鼠标支持
vim.o.fileencodings = "utf-8,gbk"                               -- 支持编码

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
